// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcE3rFW-VFUkaXov4tdasIxSL1YsHErrw',
    appId: '1:340405759312:web:82ef4dbabf1d4bff95d055',
    messagingSenderId: '340405759312',
    projectId: 'secrete-santa-9ca44',
    authDomain: 'secrete-santa-9ca44.firebaseapp.com',
    storageBucket: 'secrete-santa-9ca44.firebasestorage.app',
    measurementId: 'G-KB5YED1G5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOWJzVDxlDYyy8UhxSe8JlZq4zz_yJGkU',
    appId: '1:340405759312:android:1031075322aaec5b95d055',
    messagingSenderId: '340405759312',
    projectId: 'secrete-santa-9ca44',
    storageBucket: 'secrete-santa-9ca44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABT2ca9lei6aljxFGL64hprs2LUQFAKyc',
    appId: '1:340405759312:ios:cbbbf85f3b8ade4595d055',
    messagingSenderId: '340405759312',
    projectId: 'secrete-santa-9ca44',
    storageBucket: 'secrete-santa-9ca44.firebasestorage.app',
    iosBundleId: 'com.example.secreteSanta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABT2ca9lei6aljxFGL64hprs2LUQFAKyc',
    appId: '1:340405759312:ios:cbbbf85f3b8ade4595d055',
    messagingSenderId: '340405759312',
    projectId: 'secrete-santa-9ca44',
    storageBucket: 'secrete-santa-9ca44.firebasestorage.app',
    iosBundleId: 'com.example.secreteSanta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcE3rFW-VFUkaXov4tdasIxSL1YsHErrw',
    appId: '1:340405759312:web:9b0c4bd576bb2dce95d055',
    messagingSenderId: '340405759312',
    projectId: 'secrete-santa-9ca44',
    authDomain: 'secrete-santa-9ca44.firebaseapp.com',
    storageBucket: 'secrete-santa-9ca44.firebasestorage.app',
    measurementId: 'G-YZ8G3VC5VR',
  );
}
